package airgo

const (
	ClientID                   = "client_id"
	GrantType                  = "grant_type"
	GrantTypePassword          = "password"
	AssertionType              = "assertion_type"
	AssertionTypeFacebook      = "https://graph.facebook.com/me"
	AssertionTypeGoogle        = "https://www.googleapis.com/oauth2/v1/userinfo"
	PreventAccountCreation     = "prevent_account_creation"
	PreventAccountCreationTrue = "true"
	//Listing constant
	Locale                 = "locale"
	Currency               = "currency"
	Format                 = "_format"
	FormatMinimalPricing   = "for_search_results_with_minimal_pricing"
	FormatForSearchResults = "for_search_results"
	Limit                  = "_limit"
	Offset                 = "_offset"
	FetchFacets            = "fetch_facets"
	Guests                 = "guests"
	Ib                     = "ib"
	IbAddPhotoFlow         = "ib_add_photo_flow"
	Location               = "location"
	MinBathRooms           = "min_bathrooms"
	MinBedRooms            = "min_bedrooms"
	MinBeds                = "min_beds"
	MinNumPicUrls          = "min_num_pic_urls"
	PriceMax               = "price_max"
	PriceMin               = "price_min"
	Sort                   = "sort"
	UserLat                = "user_lat"
	UserLng                = "user_lng"
)
